name: Build, Pack and Push to dockerhub.io 

on:
  push:
    branches:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Packages & Create Bundle
        run: |
          npm install
          npm run build --if-present
        working-directory: ./app    

      - name: Publish the Release Bundle
        uses: actions/upload-artifact@v2
        with:
          name: release
          path: |
            ./app/dist
            !./app/dist/**/*.txt

  package:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Download the Release Bundle
        uses: actions/download-artifact@v2
        with:
          name: release
          path: ./app/dist/

      - name: Build and Push Docker Image to GCR
        uses: RafikFarhad/push-to-gcr-github-action@v3.0.2
        with:
          gcloud_service_key: ${{ secrets.GCLOUD_SERVICE_KEY }}
          project_id: ${{ secrets.GCLOUD_PROJECT_ID }}
          image_name: usher
          image_tag: v${{GITHUB_RUN_ID}}.0.{{ GITHUB_RUN_NUMBER}}