name: Build, Pack and Push to GCR 

on:
  push:
    branches:
      - "v*.*.*"

jobs:
  build-node-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Packages & Create Bundle
        run: |
          npm install
          npm run build --if-present
        working-directory: ./google/app    

      - name: Publish the Release Bundle
        uses: actions/upload-artifact@v2
        with:
          name: release
          path: |
            ./google/app/dist
            !./google/app/dist/**/*.txt

  create-docker-image:
    needs: build-node-package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Download the Release Bundle
        uses: actions/download-artifact@v2
        with:
          name: release
          path: ./google/app/dist/

      - name: "Build & Push Container image to Google Cloud Registry"
        shell: bash
        run: |
          BRANCH_NAME="echo $GITHUB_REF | xargs -I{} basename {}"
          docker login -u _json_key -p '${{ secrets.GCLOUD_SERVICE_KEY }}' 'https://gcr.io'
          docker build . -t gcr.io/${{ secrets.GCLOUD_PROJECT_ID }}/usher:$BRANCH_NAME-$GITHUB_RUN_NUMBER
          docker push gcr.io/${{ secrets.GCLOUD_PROJECT_ID }}/usher:v1.0.$BRANCH_NAME-$GITHUB_RUN_NUMBER
        working-directory: ./google/app/