name: Build, Pack and Push to dockerhub.io 

on:
  push:
    branches:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Packages & Create Bundle
        run: |
          npm install
          npm run build --if-present
        working-directory: ./app    

      - name: Publish the Release Bundle
        uses: actions/upload-artifact@v2
        with:
          name: release
          path: |
            ./app/dist
            !./app/dist/**/*.txt

  package:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Download the Release Bundle
        uses: actions/download-artifact@v2
        with:
          name: release
          path: ./app/dist/

      - name: Extract Branch Name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: BRANCH_NAME


      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1


      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}


      - name: Build and Push to DockerHub
        uses: docker/build-push-action@v2
        with:
          context: ./app/
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/usher:${{steps.BRANCH_NAME.outputs.branch}}